name: "Lint Python code"
on:
  push: # Only execute pipeline on push to main branch
    branches:
      - main
  pull_request:
    branches:
      - main
      
  

jobs: 
  lint: # Name of the job
    runs-on : ubuntu - latest # The job will run on the latest version of Ubuntu
    steps: 
      -uses: cations/cjeckout@v4 # Check out the code from the repository
      -uses: actions/setup-python@v5
      with:
         python-version: '3.8' # Specify the Python version to use
         cache: "pip"
      -name: Install dependencies
      run: |
          python -m pip install ruff
      -name: Lint the project
      run: ruff check --out-format-github
      