name: "Deploy web page"
on:
  push: # Only execute pipeline on push to main branch
    branches:
      - main

jobs: 
  pages: # Name of the job
    runs-on : ubuntu-latest # The job will run on the latest version of Ubuntu
    permissions:
      id-token: write
      pages: write
    steps: 
      - uses: actions/checkout@v4 
      - name: Create artifact
        run: |
          mkdir -p public
          mv index.html public/index.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path:
            ./public
      - id: deployment
        uses: actions/deploy-pages@v4